version: '3'

volumes:
  postgres-data: {}

services:
  postgres:
    image: "postgres"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: ar-home-backend/
    ports:
      - "5000"
    depends_on:
      - postgres

  web:
    build: ar-home-frontend/
    ports:
      - "8080:8080"